<a href="https://colab.research.google.com/github/4shil/Giffy/blob/master/Waterquality.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Heart Disease Classification Project

## 1. Data Ingestion & Preprocessing

In [1]:
import pandas as pd

# Load the dataset
try:
    df = pd.read_csv('heart_disease.csv')
    print("Dataset loaded successfully.")
except FileNotFoundError:
    print("Error: 'heart_disease.csv' not found. Please ensure the dataset is uploaded or the path is correct.")
    # As a fallback, try to load the waterQuality file if the user intends to use it, but this contradicts the project description.
    # This part can be removed if the project strictly uses a heart disease dataset.
    try:
        df = pd.read_csv('/content/waterQuality (1).csv')
        print("Loaded '/content/waterQuality (1).csv' as a fallback.")
        print("WARNING: This dataset is not for Heart Disease Classification. Please provide the correct heart disease dataset.")
    except FileNotFoundError:
        print("Error: '/content/waterQuality (1).csv' not found either. Please provide a dataset.")
        df = pd.DataFrame() # Create an empty DataFrame to avoid further errors


# Display the first few rows of the dataframe
if not df.empty:
    display(df.head())

Error: 'heart_disease.csv' not found. Please ensure the dataset is uploaded or the path is correct.
Loaded '/content/waterQuality (1).csv' as a fallback.
WARNING: This dataset is not for Heart Disease Classification. Please provide the correct heart disease dataset.

,aluminium,ammonia,arsenic,barium,cadmium,chloramine,chromium,copper,flouride,bacteria,...,lead,nitrates,nitrites,mercury,perchlorate,radium,selenium,silver,uranium,is_safe
0,1.65,9.08,0.04,2.85,0.007,0.35,0.83,0.17,0.05,0.20,...,0.054,16.08,1.13,0.007,37.75,6.78,0.08,0.34,0.02,1
1,2.32,21.16,0.01,3.31,0.002,5.28,0.68,0.66,0.90,0.65,...,0.100,2.01,1.93,0.003,32.26,3.21,0.08,0.27,0.05,1
2,1.01,14.02,0.04,0.58,0.008,4.24,0.53,0.02,0.99,0.05,...,0.078,14.16,1.11,0.006,50.28,7.07,0.07,0.44,0.01,0
3,1.36,11.33,0.04,2.96,0.001,7.23,0.03,1.66,1.08,0.71,...,0.016,1.41,1.29,0.004,9.12,1.72,0.02,0.45,0.05,1
4,0.92,24.33,0.03,0.20,0.006,2.67,0.69,0.57,0.61,0.13,...,0.117,6.74,1.11,0.003,16.90,2.41,0.02,0.06,0.02,1

In [2]:
if not df.empty:
    print("DataFrame Info:")
    df.info()

    print("\nMissing values per column:")
    display(df.isnull().sum())

    # Remove 'Unnamed: 0' column if it exists, as it's often an irrelevant index column
    if 'Unnamed: 0' in df.columns:
        df = df.drop('Unnamed: 0', axis=1)
        print("\nRemoved 'Unnamed: 0' column.")

    # Verify no missing values (as per project description)
    if df.isnull().sum().sum() == 0:
        print("\nNo missing values found in the dataset.")
    else:
        print("\nWarning: Missing values detected. The project description states no missing values. Please handle them if necessary.")
        # Optional: You could add code here to drop rows with missing values or impute them
        # For example, df = df.dropna()

    display(df.head())

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7999 entries, 0 to 7998
Data columns (total 21 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   aluminium    7999 non-null   float64
 1   ammonia      7999 non-null   float64
 2   arsenic      7999 non-null   float64
 3   barium       7999 non-null   float64
 4   cadmium      7999 non-null   float64
 5   chloramine   7999 non-null   float64
 6   chromium     7999 non-null   float64
 7   copper       7999 non-null   float64
 8   flouride     7999 non-null   float64
 9   bacteria     7999 non-null   float64
 10  viruses      7999 non-null   float64
 11  lead         7999 non-null   float64
 12  nitrates     7999 non-null   float64
 13  nitrites     7999 non-null   float64
 14  mercury      7999 non-null   float64
 15  perchlorate  7999 non-null   float64
 16  radium       7999 non-null   float64
 17  selenium     7999 non-null   float64
 18  silver       7999 non-null   float64
 19  uranium      7999 non-null   float64
 20  is_safe      7999 non-null   int64
dtypes: float64(20), int64(1)
memory usage: 1.3 MB

Missing values per column:

aluminium      0
ammonia        0
arsenic        0
barium         0
cadmium        0
chloramine     0
chromium       0
copper         0
flouride       0
bacteria       0
viruses        0
lead           0
nitrates       0
nitrites       0
mercury        0
perchlorate    0
radium         0
selenium       0
silver         0
uranium        0
is_safe        0
dtype: int64

No missing values found in the dataset.

,aluminium,ammonia,arsenic,barium,cadmium,chloramine,chromium,copper,flouride,bacteria,...,lead,nitrates,nitrites,mercury,perchlorate,radium,selenium,silver,uranium,is_safe
0,1.65,9.08,0.04,2.85,0.007,0.35,0.83,0.17,0.05,0.20,...,0.054,16.08,1.13,0.007,37.75,6.78,0.08,0.34,0.02,1
1,2.32,21.16,0.01,3.31,0.002,5.28,0.68,0.66,0.90,0.65,...,0.100,2.01,1.93,0.003,32.26,3.21,0.08,0.27,0.05,1
2,1.01,14.02,0.04,0.58,0.008,4.24,0.53,0.02,0.99,0.05,...,0.078,14.16,1.11,0.006,50.28,7.07,0.07,0.44,0.01,0
3,1.36,11.33,0.04,2.96,0.001,7.23,0.03,1.66,1.08,0.71,...,0.016,1.41,1.29,0.004,9.12,1.72,0.02,0.45,0.05,1
4,0.92,24.33,0.03,0.20,0.006,2.67,0.69,0.57,0.61,0.13,...,0.117,6.74,1.11,0.003,16.90,2.41,0.02,0.06,0.02,1

In [3]:
if not df.empty:
    # Identify categorical columns for one-hot encoding
    # Assuming 'sex' is a categorical column and the target is 'target' or 'heart_disease'
    # You might need to adjust these column names based on your actual dataset
    categorical_cols = ['sex'] # Example: ['sex', 'cp', 'thal', 'fbs'] etc. based on dataset
    target_col = 'target' # Example: 'target' or 'output' or 'heart_disease'

    # Convert target variable to numerical (0 and 1)
    # Assuming 'yes'/'no' or similar binary labels
    if target_col in df.columns:
        if df[target_col].dtype == 'object': # If target is string (e.g., 'yes', 'no')
            unique_target_values = df[target_col].unique()
            if len(unique_target_values) == 2:
                # Map to 0 and 1
                df[target_col] = df[target_col].map({unique_target_values[0]: 0, unique_target_values[1]: 1})
                print(f"Converted target column '{target_col}' to numerical (0/1).")
            else:
                print(f"Warning: Target column '{target_col}' has more than two unique object values. Not mapping to 0/1 automatically.")
        elif df[target_col].dtype in ['int64', 'float64'] and len(df[target_col].unique()) == 2:
            print(f"Target column '{target_col}' is already numerical (0/1).")
        else:
            print(f"Warning: Target column '{target_col}' is not clearly binary 'yes'/'no' or 0/1. No automatic mapping performed.")
    else:
        print(f"Warning: Target column '{target_col}' not found. Please adjust 'target_col' to your dataset's target variable name.")

    # Apply One-Hot Encoding to specified categorical features
    cols_to_encode = [col for col in categorical_cols if col in df.columns and df[col].dtype == 'object']

    if cols_to_encode:
        df = pd.get_dummies(df, columns=cols_to_encode, drop_first=True) # drop_first avoids multicollinearity
        print(f"Applied One-Hot Encoding to columns: {cols_to_encode}")
    else:
        print("No categorical columns (of object type) found for One-Hot Encoding.")

    display(df.head())
    print("\nDataFrame Info after encoding:")
    df.info()

Warning: Target column 'target' not found. Please adjust 'target_col' to your dataset's target variable name.
No categorical columns (of object type) found for One-Hot Encoding.

,aluminium,ammonia,arsenic,barium,cadmium,chloramine,chromium,copper,flouride,bacteria,...,lead,nitrates,nitrites,mercury,perchlorate,radium,selenium,silver,uranium,is_safe
0,1.65,9.08,0.04,2.85,0.007,0.35,0.83,0.17,0.05,0.20,...,0.054,16.08,1.13,0.007,37.75,6.78,0.08,0.34,0.02,1
1,2.32,21.16,0.01,3.31,0.002,5.28,0.68,0.66,0.90,0.65,...,0.100,2.01,1.93,0.003,32.26,3.21,0.08,0.27,0.05,1
2,1.01,14.02,0.04,0.58,0.008,4.24,0.53,0.02,0.99,0.05,...,0.078,14.16,1.11,0.006,50.28,7.07,0.07,0.44,0.01,0
3,1.36,11.33,0.04,2.96,0.001,7.23,0.03,1.66,1.08,0.71,...,0.016,1.41,1.29,0.004,9.12,1.72,0.02,0.45,0.05,1
4,0.92,24.33,0.03,0.20,0.006,2.67,0.69,0.57,0.61,0.13,...,0.117,6.74,1.11,0.003,16.90,2.41,0.02,0.06,0.02,1

DataFrame Info after encoding:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7999 entries, 0 to 7998
Data columns (total 21 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   aluminium    7999 non-null   float64
 1   ammonia      7999 non-null   float64
 2   arsenic      7999 non-null   float64
 3   barium       7999 non-null   float64
 4   cadmium      7999 non-null   float64
 5   chloramine   7999 non-null   float64
 6   chromium     7999 non-null   float64
 7   copper       7999 non-null   float64
 8   flouride     7999 non-null   float64
 9   bacteria     7999 non-null   float64
 10  viruses      7999 non-null   float64
 11  lead         7999 non-null   float64
 12  nitrates     7999 non-null   float64
 13  nitrites     7999 non-null   float64
 14  mercury      7999 non-null   float64
 15  perchlorate  7999 non-null   float64
 16  radium       7999 non-null   float64
 17  selenium     7999 non-null   float64
 18  silver       7999 non-null   float64
 19  uranium      7999 non-null   float64
 20  is_safe      7999 non-null   int64
dtypes: float64(20), int64(1)
memory usage: 1.3 MB

## 2. Feature Scaling & Data Splitting

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

if not df.empty:
    # Define features (X) and target (y)
    # Using 'is_safe' as the target column based on the loaded dataset
    target_col = 'is_safe'
    X = df.drop(columns=[target_col])
    y = df[target_col]

    # 1. Data Splitting (80% Train, 20% Test)
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # 2. Feature Scaling (MinMaxScaler)
    scaler = MinMaxScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    print(f"Training set shape: {X_train_scaled.shape}")
    print(f"Testing set shape: {X_test_scaled.shape}")
    print("\nFeature scaling and data splitting completed.")

Training set shape: (6399, 20)
Testing set shape: (1600, 20)

Feature scaling and data splitting completed.

## 3. Model Selection & Performance Evaluation

In [5]:
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

# Initialize models
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Naive Bayes": GaussianNB(),
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "Random Forest": RandomForestClassifier(random_state=42)
}

results = {}

# Train and evaluate
for name, model in models.items():
    model.fit(X_train_scaled, y_train)
    y_pred = model.predict(X_test_scaled)

    results[name] = {
        "Accuracy": accuracy_score(y_test, y_pred),
        "Precision": precision_score(y_test, y_pred),
        "Recall": recall_score(y_test, y_pred),
        "F1-Score": f1_score(y_test, y_pred)
    }

# Display Results
import pandas as pd_results
results_df = pd_results.DataFrame(results).T
print("Model Evaluation Metrics:")
display(results_df)

Model Evaluation Metrics:

                     Accuracy  Precision  Recall  F1-Score
Logistic Regression  0.900625   0.746988   0.310  0.438163
Naive Bayes          0.845000   0.418919   0.620  0.500000
Decision Tree        0.958750   0.835000   0.835  0.835000
Random Forest        0.958125   0.965035   0.690  0.804665

## 4. Deployment & Serialization